# Generated by Django 5.0.6 on 2024-08-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TempLang', '0002_alter_todo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-updated']},
        ),
    ]
