# Generated by Django 5.0.6 on 2024-09-01 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TempLang', '0003_alter_todo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-created', '-updated']},
        ),
    ]
